version: '3.8'

services:
  cliente-postgres:
    image: postgres:15
    container_name: cliente-postgres
    environment:
      POSTGRES_DB: cliente
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cliente-back:
    build: .
    container_name: cliente_back
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cliente
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root@123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - cliente-postgres

volumes:
  postgres_data:
