apiVersion: v1
kind: Service
metadata:
  name: cliente-cadastro-service
  labels:
    app: cliente-cadastro
spec:
  type: LoadBalancer
  selector:
    app: cliente-cadastro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
